version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: li13451234
      MYSQL_DATABASE: admin
      MYSQL_USER: user
      MYSQL_PASSWORD: li13451234
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: li13451234
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
