// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: api/api_db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DBApiUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty" gorm:"primary_key;autoIncrement"` //账号
	Password string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                                //密码
	Identity Identity `protobuf:"varint,3,opt,name=identity,proto3,enum=Identity" json:"identity,omitempty"`                 //身份
}

func (x *DBApiUser) Reset() {
	*x = DBApiUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBApiUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBApiUser) ProtoMessage() {}

func (x *DBApiUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBApiUser.ProtoReflect.Descriptor instead.
func (*DBApiUser) Descriptor() ([]byte, []int) {
	return file_api_api_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBApiUser) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *DBApiUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DBApiUser) GetIdentity() Identity {
	if x != nil {
		return x.Identity
	}
	return Identity_IdentityNull
}

var File_api_api_db_proto protoreflect.FileDescriptor

var file_api_api_db_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68,
	0x0a, 0x09, 0x44, 0x42, 0x41, 0x70, 0x69, 0x55, 0x73, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x25, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_api_db_proto_rawDescOnce sync.Once
	file_api_api_db_proto_rawDescData = file_api_api_db_proto_rawDesc
)

func file_api_api_db_proto_rawDescGZIP() []byte {
	file_api_api_db_proto_rawDescOnce.Do(func() {
		file_api_api_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_api_db_proto_rawDescData)
	})
	return file_api_api_db_proto_rawDescData
}

var file_api_api_db_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_api_db_proto_goTypes = []interface{}{
	(*DBApiUser)(nil), // 0: DBApiUser
	(Identity)(0),     // 1: Identity
}
var file_api_api_db_proto_depIdxs = []int32{
	1, // 0: DBApiUser.identity:type_name -> Identity
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_api_db_proto_init() }
func file_api_api_db_proto_init() {
	if File_api_api_db_proto != nil {
		return
	}
	file_enum_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_api_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBApiUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_api_db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_api_db_proto_goTypes,
		DependencyIndexes: file_api_api_db_proto_depIdxs,
		MessageInfos:      file_api_api_db_proto_msgTypes,
	}.Build()
	File_api_api_db_proto = out.File
	file_api_api_db_proto_rawDesc = nil
	file_api_api_db_proto_goTypes = nil
	file_api_api_db_proto_depIdxs = nil
}
