// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: rpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPC_EmptyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RPC_EmptyReq) Reset() {
	*x = RPC_EmptyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPC_EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC_EmptyReq) ProtoMessage() {}

func (x *RPC_EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC_EmptyReq.ProtoReflect.Descriptor instead.
func (*RPC_EmptyReq) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

type RPC_EmptyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RPC_EmptyResp) Reset() {
	*x = RPC_EmptyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPC_EmptyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC_EmptyResp) ProtoMessage() {}

func (x *RPC_EmptyResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC_EmptyResp.ProtoReflect.Descriptor instead.
func (*RPC_EmptyResp) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

// RPC向用户代理发送消息请求
type Rpc_GatewayRouteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgName     string           `protobuf:"bytes,1,opt,name=MsgName,proto3" json:"MsgName,omitempty"`
	UserSession *UserSessionData `protobuf:"bytes,3,opt,name=UserSession,proto3" json:"UserSession,omitempty"`
	Message     *anypb.Any       `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *Rpc_GatewayRouteReq) Reset() {
	*x = Rpc_GatewayRouteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewayRouteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewayRouteReq) ProtoMessage() {}

func (x *Rpc_GatewayRouteReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewayRouteReq.ProtoReflect.Descriptor instead.
func (*Rpc_GatewayRouteReq) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *Rpc_GatewayRouteReq) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *Rpc_GatewayRouteReq) GetUserSession() *UserSessionData {
	if x != nil {
		return x.UserSession
	}
	return nil
}

func (x *Rpc_GatewayRouteReq) GetMessage() *anypb.Any {
	if x != nil {
		return x.Message
	}
	return nil
}

// RPC服务固定回复结构
type Rpc_GatewayRouteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServicePath string         `protobuf:"bytes,1,opt,name=ServicePath,proto3" json:"ServicePath,omitempty"`
	ErrorData   *ErrorData     `protobuf:"bytes,2,opt,name=ErrorData,proto3" json:"ErrorData,omitempty"`
	Reply       []*UserMessage `protobuf:"bytes,3,rep,name=Reply,proto3" json:"Reply,omitempty"`
}

func (x *Rpc_GatewayRouteResp) Reset() {
	*x = Rpc_GatewayRouteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewayRouteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewayRouteResp) ProtoMessage() {}

func (x *Rpc_GatewayRouteResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewayRouteResp.ProtoReflect.Descriptor instead.
func (*Rpc_GatewayRouteResp) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *Rpc_GatewayRouteResp) GetServicePath() string {
	if x != nil {
		return x.ServicePath
	}
	return ""
}

func (x *Rpc_GatewayRouteResp) GetErrorData() *ErrorData {
	if x != nil {
		return x.ErrorData
	}
	return nil
}

func (x *Rpc_GatewayRouteResp) GetReply() []*UserMessage {
	if x != nil {
		return x.Reply
	}
	return nil
}

// RPC向用户代理发送消息
type Rpc_GatewayAgentSendMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSessionId string         `protobuf:"bytes,1,opt,name=UserSessionId,proto3" json:"UserSessionId,omitempty"`
	Reply         []*UserMessage `protobuf:"bytes,2,rep,name=Reply,proto3" json:"Reply,omitempty"`
}

func (x *Rpc_GatewayAgentSendMsgReq) Reset() {
	*x = Rpc_GatewayAgentSendMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewayAgentSendMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewayAgentSendMsgReq) ProtoMessage() {}

func (x *Rpc_GatewayAgentSendMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewayAgentSendMsgReq.ProtoReflect.Descriptor instead.
func (*Rpc_GatewayAgentSendMsgReq) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *Rpc_GatewayAgentSendMsgReq) GetUserSessionId() string {
	if x != nil {
		return x.UserSessionId
	}
	return ""
}

func (x *Rpc_GatewayAgentSendMsgReq) GetReply() []*UserMessage {
	if x != nil {
		return x.Reply
	}
	return nil
}

type Rpc_GatewayAgentSendMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorData *ErrorData `protobuf:"bytes,1,opt,name=ErrorData,proto3" json:"ErrorData,omitempty"`
}

func (x *Rpc_GatewayAgentSendMsgResp) Reset() {
	*x = Rpc_GatewayAgentSendMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewayAgentSendMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewayAgentSendMsgResp) ProtoMessage() {}

func (x *Rpc_GatewayAgentSendMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewayAgentSendMsgResp.ProtoReflect.Descriptor instead.
func (*Rpc_GatewayAgentSendMsgResp) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *Rpc_GatewayAgentSendMsgResp) GetErrorData() *ErrorData {
	if x != nil {
		return x.ErrorData
	}
	return nil
}

//RPC向多用户代理发送消息
type Rpc_GatewaySendBatchMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSessionIds []string   `protobuf:"bytes,1,rep,name=UserSessionIds,proto3" json:"UserSessionIds,omitempty"`
	MsgName        string     `protobuf:"bytes,2,opt,name=MsgName,proto3" json:"MsgName,omitempty"`
	Data           *anypb.Any `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Rpc_GatewaySendBatchMsgReq) Reset() {
	*x = Rpc_GatewaySendBatchMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewaySendBatchMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewaySendBatchMsgReq) ProtoMessage() {}

func (x *Rpc_GatewaySendBatchMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewaySendBatchMsgReq.ProtoReflect.Descriptor instead.
func (*Rpc_GatewaySendBatchMsgReq) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *Rpc_GatewaySendBatchMsgReq) GetUserSessionIds() []string {
	if x != nil {
		return x.UserSessionIds
	}
	return nil
}

func (x *Rpc_GatewaySendBatchMsgReq) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *Rpc_GatewaySendBatchMsgReq) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type Rpc_GatewaySendBatchMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorData *ErrorData `protobuf:"bytes,1,opt,name=ErrorData,proto3" json:"ErrorData,omitempty"`
}

func (x *Rpc_GatewaySendBatchMsgResp) Reset() {
	*x = Rpc_GatewaySendBatchMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewaySendBatchMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewaySendBatchMsgResp) ProtoMessage() {}

func (x *Rpc_GatewaySendBatchMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewaySendBatchMsgResp.ProtoReflect.Descriptor instead.
func (*Rpc_GatewaySendBatchMsgResp) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *Rpc_GatewaySendBatchMsgResp) GetErrorData() *ErrorData {
	if x != nil {
		return x.ErrorData
	}
	return nil
}

//发送批量消息
type Rpc_GatewaySendBatchMsgsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgName string                `protobuf:"bytes,1,opt,name=MsgName,proto3" json:"MsgName,omitempty"`
	Data    map[string]*anypb.Any `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Rpc_GatewaySendBatchMsgsReq) Reset() {
	*x = Rpc_GatewaySendBatchMsgsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewaySendBatchMsgsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewaySendBatchMsgsReq) ProtoMessage() {}

func (x *Rpc_GatewaySendBatchMsgsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewaySendBatchMsgsReq.ProtoReflect.Descriptor instead.
func (*Rpc_GatewaySendBatchMsgsReq) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *Rpc_GatewaySendBatchMsgsReq) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *Rpc_GatewaySendBatchMsgsReq) GetData() map[string]*anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

//发送批量消息
type Rpc_GatewaySendBatchMsgsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorData *ErrorData `protobuf:"bytes,1,opt,name=ErrorData,proto3" json:"ErrorData,omitempty"`
}

func (x *Rpc_GatewaySendBatchMsgsResp) Reset() {
	*x = Rpc_GatewaySendBatchMsgsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewaySendBatchMsgsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewaySendBatchMsgsResp) ProtoMessage() {}

func (x *Rpc_GatewaySendBatchMsgsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewaySendBatchMsgsResp.ProtoReflect.Descriptor instead.
func (*Rpc_GatewaySendBatchMsgsResp) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *Rpc_GatewaySendBatchMsgsResp) GetErrorData() *ErrorData {
	if x != nil {
		return x.ErrorData
	}
	return nil
}

//广播消息
type Rpc_GatewaySendRadioMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgName string     `protobuf:"bytes,1,opt,name=MsgName,proto3" json:"MsgName,omitempty"`
	Data    *anypb.Any `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Rpc_GatewaySendRadioMsgReq) Reset() {
	*x = Rpc_GatewaySendRadioMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewaySendRadioMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewaySendRadioMsgReq) ProtoMessage() {}

func (x *Rpc_GatewaySendRadioMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewaySendRadioMsgReq.ProtoReflect.Descriptor instead.
func (*Rpc_GatewaySendRadioMsgReq) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *Rpc_GatewaySendRadioMsgReq) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *Rpc_GatewaySendRadioMsgReq) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

//广播消息
type Rpc_GatewaySendRadioMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Rpc_GatewaySendRadioMsgResp) Reset() {
	*x = Rpc_GatewaySendRadioMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewaySendRadioMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewaySendRadioMsgResp) ProtoMessage() {}

func (x *Rpc_GatewaySendRadioMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewaySendRadioMsgResp.ProtoReflect.Descriptor instead.
func (*Rpc_GatewaySendRadioMsgResp) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{11}
}

//向目标用户发送消息
type Rpc_GatewaySendBatchMsgByUidReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgName string     `protobuf:"bytes,1,opt,name=MsgName,proto3" json:"MsgName,omitempty"`
	Uids    []string   `protobuf:"bytes,2,rep,name=uids,proto3" json:"uids,omitempty"`
	Data    *anypb.Any `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Rpc_GatewaySendBatchMsgByUidReq) Reset() {
	*x = Rpc_GatewaySendBatchMsgByUidReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewaySendBatchMsgByUidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewaySendBatchMsgByUidReq) ProtoMessage() {}

func (x *Rpc_GatewaySendBatchMsgByUidReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewaySendBatchMsgByUidReq.ProtoReflect.Descriptor instead.
func (*Rpc_GatewaySendBatchMsgByUidReq) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *Rpc_GatewaySendBatchMsgByUidReq) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *Rpc_GatewaySendBatchMsgByUidReq) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

func (x *Rpc_GatewaySendBatchMsgByUidReq) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type Rpc_GatewaySendBatchMsgByUidResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Rpc_GatewaySendBatchMsgByUidResp) Reset() {
	*x = Rpc_GatewaySendBatchMsgByUidResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewaySendBatchMsgByUidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewaySendBatchMsgByUidResp) ProtoMessage() {}

func (x *Rpc_GatewaySendBatchMsgByUidResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewaySendBatchMsgByUidResp.ProtoReflect.Descriptor instead.
func (*Rpc_GatewaySendBatchMsgByUidResp) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{13}
}

//关闭用户代理
type Rpc_GatewayAgentCloseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSessionId string `protobuf:"bytes,1,opt,name=UserSessionId,proto3" json:"UserSessionId,omitempty"`
}

func (x *Rpc_GatewayAgentCloseReq) Reset() {
	*x = Rpc_GatewayAgentCloseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewayAgentCloseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewayAgentCloseReq) ProtoMessage() {}

func (x *Rpc_GatewayAgentCloseReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewayAgentCloseReq.ProtoReflect.Descriptor instead.
func (*Rpc_GatewayAgentCloseReq) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *Rpc_GatewayAgentCloseReq) GetUserSessionId() string {
	if x != nil {
		return x.UserSessionId
	}
	return ""
}

type Rpc_GatewayAgentCloseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Rpc_GatewayAgentCloseResp) Reset() {
	*x = Rpc_GatewayAgentCloseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewayAgentCloseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewayAgentCloseResp) ProtoMessage() {}

func (x *Rpc_GatewayAgentCloseResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewayAgentCloseResp.ProtoReflect.Descriptor instead.
func (*Rpc_GatewayAgentCloseResp) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{15}
}

//用户代理解绑账号
type Rpc_GatewayAgentUnBindReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSessionId string `protobuf:"bytes,1,opt,name=UserSessionId,proto3" json:"UserSessionId,omitempty"`
}

func (x *Rpc_GatewayAgentUnBindReq) Reset() {
	*x = Rpc_GatewayAgentUnBindReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewayAgentUnBindReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewayAgentUnBindReq) ProtoMessage() {}

func (x *Rpc_GatewayAgentUnBindReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewayAgentUnBindReq.ProtoReflect.Descriptor instead.
func (*Rpc_GatewayAgentUnBindReq) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{16}
}

func (x *Rpc_GatewayAgentUnBindReq) GetUserSessionId() string {
	if x != nil {
		return x.UserSessionId
	}
	return ""
}

type Rpc_GatewayAgentUnBindResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Rpc_GatewayAgentUnBindResp) Reset() {
	*x = Rpc_GatewayAgentUnBindResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewayAgentUnBindResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewayAgentUnBindResp) ProtoMessage() {}

func (x *Rpc_GatewayAgentUnBindResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewayAgentUnBindResp.ProtoReflect.Descriptor instead.
func (*Rpc_GatewayAgentUnBindResp) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{17}
}

//通知用户离线
type RPC_Gateway_NoticeUserCloseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSession *UserSessionData `protobuf:"bytes,1,opt,name=UserSession,proto3" json:"UserSession,omitempty"`
}

func (x *RPC_Gateway_NoticeUserCloseReq) Reset() {
	*x = RPC_Gateway_NoticeUserCloseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPC_Gateway_NoticeUserCloseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC_Gateway_NoticeUserCloseReq) ProtoMessage() {}

func (x *RPC_Gateway_NoticeUserCloseReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC_Gateway_NoticeUserCloseReq.ProtoReflect.Descriptor instead.
func (*RPC_Gateway_NoticeUserCloseReq) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{18}
}

func (x *RPC_Gateway_NoticeUserCloseReq) GetUserSession() *UserSessionData {
	if x != nil {
		return x.UserSession
	}
	return nil
}

type RPC_Gateway_NoticeUserCloseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RPC_Gateway_NoticeUserCloseResp) Reset() {
	*x = RPC_Gateway_NoticeUserCloseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPC_Gateway_NoticeUserCloseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC_Gateway_NoticeUserCloseResp) ProtoMessage() {}

func (x *RPC_Gateway_NoticeUserCloseResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC_Gateway_NoticeUserCloseResp.ProtoReflect.Descriptor instead.
func (*RPC_Gateway_NoticeUserCloseResp) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{19}
}

//网关Http 路由请求
type Rpc_GatewayHttpRouteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgName string `protobuf:"bytes,1,opt,name=MsgName,proto3" json:"MsgName,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Message []byte `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *Rpc_GatewayHttpRouteReq) Reset() {
	*x = Rpc_GatewayHttpRouteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewayHttpRouteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewayHttpRouteReq) ProtoMessage() {}

func (x *Rpc_GatewayHttpRouteReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewayHttpRouteReq.ProtoReflect.Descriptor instead.
func (*Rpc_GatewayHttpRouteReq) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{20}
}

func (x *Rpc_GatewayHttpRouteReq) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *Rpc_GatewayHttpRouteReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Rpc_GatewayHttpRouteReq) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type Rpc_GatewayHttpRouteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorData *ErrorData `protobuf:"bytes,1,opt,name=ErrorData,proto3" json:"ErrorData,omitempty"`
	Data      *anypb.Any `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Rpc_GatewayHttpRouteResp) Reset() {
	*x = Rpc_GatewayHttpRouteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewayHttpRouteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewayHttpRouteResp) ProtoMessage() {}

func (x *Rpc_GatewayHttpRouteResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewayHttpRouteResp.ProtoReflect.Descriptor instead.
func (*Rpc_GatewayHttpRouteResp) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{21}
}

func (x *Rpc_GatewayHttpRouteResp) GetErrorData() *ErrorData {
	if x != nil {
		return x.ErrorData
	}
	return nil
}

func (x *Rpc_GatewayHttpRouteResp) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_rpc_proto protoreflect.FileDescriptor

var file_rpc_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x63, 0x6f, 0x6d,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x50, 0x43, 0x5f, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x50, 0x43, 0x5f, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x93, 0x01, 0x0a, 0x13, 0x52, 0x70, 0x63, 0x5f, 0x47, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x4d,
	0x73, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x73,
	0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0b, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79,
	0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x14, 0x52, 0x70,
	0x63, 0x5f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x28, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22,
	0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x66, 0x0a, 0x1a, 0x52, 0x70, 0x63, 0x5f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71,
	0x12, 0x24, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x47, 0x0a, 0x1b, 0x52, 0x70,
	0x63, 0x5f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x09, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x88, 0x01, 0x0a, 0x1a, 0x52, 0x70, 0x63, 0x5f, 0x47, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x71, 0x12, 0x26, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73,
	0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x73, 0x67,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x47,
	0x0a, 0x1b, 0x52, 0x70, 0x63, 0x5f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65, 0x6e,
	0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a,
	0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22, 0xc2, 0x01, 0x0a, 0x1b, 0x52, 0x70, 0x63, 0x5f,
	0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x4d, 0x73, 0x67, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x3a, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x52, 0x70, 0x63, 0x5f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65, 0x6e,
	0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x73, 0x52, 0x65, 0x71, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x4d, 0x0a,
	0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x48, 0x0a, 0x1c,
	0x52, 0x70, 0x63, 0x5f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65, 0x6e, 0x64, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x09,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22, 0x60, 0x0a, 0x1a, 0x52, 0x70, 0x63, 0x5f, 0x47, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x61, 0x64, 0x69, 0x6f, 0x4d, 0x73,
	0x67, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x1d, 0x0a, 0x1b, 0x52, 0x70, 0x63, 0x5f,
	0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x61, 0x64, 0x69, 0x6f,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0x79, 0x0a, 0x1f, 0x52, 0x70, 0x63, 0x5f, 0x47,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4d,
	0x73, 0x67, 0x42, 0x79, 0x55, 0x69, 0x64, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73,
	0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x73, 0x67,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73, 0x12, 0x28, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x22, 0x0a, 0x20, 0x52, 0x70, 0x63, 0x5f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x42, 0x79, 0x55,
	0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x40, 0x0a, 0x18, 0x52, 0x70, 0x63, 0x5f, 0x47, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x24, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x52, 0x70, 0x63, 0x5f,
	0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x41, 0x0a, 0x19, 0x52, 0x70, 0x63, 0x5f, 0x47, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x42, 0x69, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x24, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x1c, 0x0a, 0x1a, 0x52, 0x70, 0x63, 0x5f,
	0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x42, 0x69,
	0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x54, 0x0a, 0x1e, 0x52, 0x50, 0x43, 0x5f, 0x47, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x32, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x21, 0x0a, 0x1f,
	0x52, 0x50, 0x43, 0x5f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x4e, 0x6f, 0x74, 0x69,
	0x63, 0x65, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x65, 0x0a, 0x17, 0x52, 0x70, 0x63, 0x5f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x48, 0x74,
	0x74, 0x70, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73,
	0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x73, 0x67,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x6e, 0x0a, 0x18, 0x52, 0x70, 0x63, 0x5f, 0x47, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x48, 0x74, 0x74, 0x70, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x28, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x28, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79,
	0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData = file_rpc_proto_rawDesc
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_proto_rawDescData)
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_rpc_proto_goTypes = []interface{}{
	(*RPC_EmptyReq)(nil),                     // 0: RPC_EmptyReq
	(*RPC_EmptyResp)(nil),                    // 1: RPC_EmptyResp
	(*Rpc_GatewayRouteReq)(nil),              // 2: Rpc_GatewayRouteReq
	(*Rpc_GatewayRouteResp)(nil),             // 3: Rpc_GatewayRouteResp
	(*Rpc_GatewayAgentSendMsgReq)(nil),       // 4: Rpc_GatewayAgentSendMsgReq
	(*Rpc_GatewayAgentSendMsgResp)(nil),      // 5: Rpc_GatewayAgentSendMsgResp
	(*Rpc_GatewaySendBatchMsgReq)(nil),       // 6: Rpc_GatewaySendBatchMsgReq
	(*Rpc_GatewaySendBatchMsgResp)(nil),      // 7: Rpc_GatewaySendBatchMsgResp
	(*Rpc_GatewaySendBatchMsgsReq)(nil),      // 8: Rpc_GatewaySendBatchMsgsReq
	(*Rpc_GatewaySendBatchMsgsResp)(nil),     // 9: Rpc_GatewaySendBatchMsgsResp
	(*Rpc_GatewaySendRadioMsgReq)(nil),       // 10: Rpc_GatewaySendRadioMsgReq
	(*Rpc_GatewaySendRadioMsgResp)(nil),      // 11: Rpc_GatewaySendRadioMsgResp
	(*Rpc_GatewaySendBatchMsgByUidReq)(nil),  // 12: Rpc_GatewaySendBatchMsgByUidReq
	(*Rpc_GatewaySendBatchMsgByUidResp)(nil), // 13: Rpc_GatewaySendBatchMsgByUidResp
	(*Rpc_GatewayAgentCloseReq)(nil),         // 14: Rpc_GatewayAgentCloseReq
	(*Rpc_GatewayAgentCloseResp)(nil),        // 15: Rpc_GatewayAgentCloseResp
	(*Rpc_GatewayAgentUnBindReq)(nil),        // 16: Rpc_GatewayAgentUnBindReq
	(*Rpc_GatewayAgentUnBindResp)(nil),       // 17: Rpc_GatewayAgentUnBindResp
	(*RPC_Gateway_NoticeUserCloseReq)(nil),   // 18: RPC_Gateway_NoticeUserCloseReq
	(*RPC_Gateway_NoticeUserCloseResp)(nil),  // 19: RPC_Gateway_NoticeUserCloseResp
	(*Rpc_GatewayHttpRouteReq)(nil),          // 20: Rpc_GatewayHttpRouteReq
	(*Rpc_GatewayHttpRouteResp)(nil),         // 21: Rpc_GatewayHttpRouteResp
	nil,                                      // 22: Rpc_GatewaySendBatchMsgsReq.DataEntry
	(*UserSessionData)(nil),                  // 23: UserSessionData
	(*anypb.Any)(nil),                        // 24: google.protobuf.Any
	(*ErrorData)(nil),                        // 25: ErrorData
	(*UserMessage)(nil),                      // 26: UserMessage
}
var file_rpc_proto_depIdxs = []int32{
	23, // 0: Rpc_GatewayRouteReq.UserSession:type_name -> UserSessionData
	24, // 1: Rpc_GatewayRouteReq.Message:type_name -> google.protobuf.Any
	25, // 2: Rpc_GatewayRouteResp.ErrorData:type_name -> ErrorData
	26, // 3: Rpc_GatewayRouteResp.Reply:type_name -> UserMessage
	26, // 4: Rpc_GatewayAgentSendMsgReq.Reply:type_name -> UserMessage
	25, // 5: Rpc_GatewayAgentSendMsgResp.ErrorData:type_name -> ErrorData
	24, // 6: Rpc_GatewaySendBatchMsgReq.Data:type_name -> google.protobuf.Any
	25, // 7: Rpc_GatewaySendBatchMsgResp.ErrorData:type_name -> ErrorData
	22, // 8: Rpc_GatewaySendBatchMsgsReq.Data:type_name -> Rpc_GatewaySendBatchMsgsReq.DataEntry
	25, // 9: Rpc_GatewaySendBatchMsgsResp.ErrorData:type_name -> ErrorData
	24, // 10: Rpc_GatewaySendRadioMsgReq.Data:type_name -> google.protobuf.Any
	24, // 11: Rpc_GatewaySendBatchMsgByUidReq.Data:type_name -> google.protobuf.Any
	23, // 12: RPC_Gateway_NoticeUserCloseReq.UserSession:type_name -> UserSessionData
	25, // 13: Rpc_GatewayHttpRouteResp.ErrorData:type_name -> ErrorData
	24, // 14: Rpc_GatewayHttpRouteResp.Data:type_name -> google.protobuf.Any
	24, // 15: Rpc_GatewaySendBatchMsgsReq.DataEntry.value:type_name -> google.protobuf.Any
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	file_comm_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPC_EmptyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPC_EmptyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewayRouteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewayRouteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewayAgentSendMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewayAgentSendMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewaySendBatchMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewaySendBatchMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewaySendBatchMsgsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewaySendBatchMsgsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewaySendRadioMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewaySendRadioMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewaySendBatchMsgByUidReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewaySendBatchMsgByUidResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewayAgentCloseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewayAgentCloseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewayAgentUnBindReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewayAgentUnBindResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPC_Gateway_NoticeUserCloseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPC_Gateway_NoticeUserCloseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewayHttpRouteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewayHttpRouteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		MessageInfos:      file_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_rawDesc = nil
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
