
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type atn struct {
    A string
    T int32
    N int64
}

const TypeId_atn = 96923

func (*atn) GetTypeId() int32 {
    return 96923
}

func Newatn(_buf map[string]interface{}) (_v *atn, err error) {
    _v = &atn{}
    { var _ok_ bool; if _v.A, _ok_ = _buf["a"].(string); !_ok_ { err = errors.New("a error"); return } }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["t"].(float64); !_ok_ { err = errors.New("t error"); return }; _v.T = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["n"].(float64); !_ok_ { err = errors.New("n error"); return }; _v.N = int64(_tempNum_) }
    return
}

