
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type atr struct {
    A int32
    N int64
}

const TypeId_atr = 96927

func (*atr) GetTypeId() int32 {
    return 96927
}

func Newatr(_buf map[string]interface{}) (_v *atr, err error) {
    _v = &atr{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["a"].(float64); !_ok_ { err = errors.New("a error"); return }; _v.A = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["n"].(float64); !_ok_ { err = errors.New("n error"); return }; _v.N = int64(_tempNum_) }
    return
}

