
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type GameBR004Conf struct {
    _dataMap map[int32]*GameBR004ConfData
    _dataList []*GameBR004ConfData
}

func NewGameBR004Conf(_buf []map[string]interface{}) (*GameBR004Conf, error) {
    _dataList := make([]*GameBR004ConfData, 0, len(_buf))
    dataMap := make(map[int32]*GameBR004ConfData)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGameBR004ConfData(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &GameBR004Conf{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *GameBR004Conf) GetDataMap() map[int32]*GameBR004ConfData {
    return table._dataMap
}

func (table *GameBR004Conf) GetDataList() []*GameBR004ConfData {
    return table._dataList
}

func (table *GameBR004Conf) Get(key int32) *GameBR004ConfData {
    return table._dataMap[key]
}


