
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 最差品质
     */
    GameColorType_WHITE = 1;
    /**
     * 蓝色的
     */
    GameColorType_BLUE = 2;
    /**
     * 紫色的
     */
    GameColorType_PURPLE = 3;
    /**
     * 最高品质
     */
    GameColorType_RED = 4;
)

