
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type GameDJ002Conf struct {
    _dataMap map[int32]*GameDJ002ConfData
    _dataList []*GameDJ002ConfData
}

func NewGameDJ002Conf(_buf []map[string]interface{}) (*GameDJ002Conf, error) {
    _dataList := make([]*GameDJ002ConfData, 0, len(_buf))
    dataMap := make(map[int32]*GameDJ002ConfData)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGameDJ002ConfData(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &GameDJ002Conf{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *GameDJ002Conf) GetDataMap() map[int32]*GameDJ002ConfData {
    return table._dataMap
}

func (table *GameDJ002Conf) GetDataList() []*GameDJ002ConfData {
    return table._dataList
}

func (table *GameDJ002Conf) Get(key int32) *GameDJ002ConfData {
    return table._dataMap[key]
}


