
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type GameBR003Room struct {
    _dataMap map[int32]*GameBR003RoomData
    _dataList []*GameBR003RoomData
}

func NewGameBR003Room(_buf []map[string]interface{}) (*GameBR003Room, error) {
    _dataList := make([]*GameBR003RoomData, 0, len(_buf))
    dataMap := make(map[int32]*GameBR003RoomData)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGameBR003RoomData(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &GameBR003Room{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *GameBR003Room) GetDataMap() map[int32]*GameBR003RoomData {
    return table._dataMap
}

func (table *GameBR003Room) GetDataList() []*GameBR003RoomData {
    return table._dataList
}

func (table *GameBR003Room) Get(key int32) *GameBR003RoomData {
    return table._dataMap[key]
}


