
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type GameGlobal struct {
    _dataMap map[int32]*GameGlobalData
    _dataList []*GameGlobalData
}

func NewGameGlobal(_buf []map[string]interface{}) (*GameGlobal, error) {
    _dataList := make([]*GameGlobalData, 0, len(_buf))
    dataMap := make(map[int32]*GameGlobalData)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGameGlobalData(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.MaxChar] = _v
        }
    }
    return &GameGlobal{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *GameGlobal) GetDataMap() map[int32]*GameGlobalData {
    return table._dataMap
}

func (table *GameGlobal) GetDataList() []*GameGlobalData {
    return table._dataList
}

func (table *GameGlobal) Get(key int32) *GameGlobalData {
    return table._dataMap[key]
}


