
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type GameBR003Conf struct {
    _dataMap map[int32]*GameBR003ConfData
    _dataList []*GameBR003ConfData
}

func NewGameBR003Conf(_buf []map[string]interface{}) (*GameBR003Conf, error) {
    _dataList := make([]*GameBR003ConfData, 0, len(_buf))
    dataMap := make(map[int32]*GameBR003ConfData)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGameBR003ConfData(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &GameBR003Conf{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *GameBR003Conf) GetDataMap() map[int32]*GameBR003ConfData {
    return table._dataMap
}

func (table *GameBR003Conf) GetDataList() []*GameBR003ConfData {
    return table._dataList
}

func (table *GameBR003Conf) Get(key int32) *GameBR003ConfData {
    return table._dataMap[key]
}


