
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 最大血量
     */
    GamePropertyType_Hp = 1;
    /**
     * 旋转速度
     */
    GamePropertyType_RotaSpeed = 2;
    /**
     * 移动速度
     */
    GamePropertyType_Speed = 3;
    /**
     * 质量
     */
    GamePropertyType_Mass = 4;
    /**
     * 伤害
     */
    GamePropertyType_Act = 5;
    /**
     * 暴击
     */
    GamePropertyType_Cri = 6;
)

