
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type GameBR002Conf struct {
    _dataMap map[int32]*GameBR002ConfData
    _dataList []*GameBR002ConfData
}

func NewGameBR002Conf(_buf []map[string]interface{}) (*GameBR002Conf, error) {
    _dataList := make([]*GameBR002ConfData, 0, len(_buf))
    dataMap := make(map[int32]*GameBR002ConfData)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGameBR002ConfData(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &GameBR002Conf{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *GameBR002Conf) GetDataMap() map[int32]*GameBR002ConfData {
    return table._dataMap
}

func (table *GameBR002Conf) GetDataList() []*GameBR002ConfData {
    return table._dataList
}

func (table *GameBR002Conf) Get(key int32) *GameBR002ConfData {
    return table._dataMap[key]
}


