
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 炸弹
     */
    GameSkillType_Bomb = 101;
    /**
     * 回复药剂
     */
    GameSkillType_Reply = 102;
    /**
     * 护盾
     */
    GameSkillType_Shields = 103;
    /**
     * 增益器
     */
    GameSkillType_Enlarge = 104;
    /**
     * 冰冻器
     */
    GameSkillType_Freezer = 105;
    /**
     * 风暴召唤器
     */
    GameSkillType_Storm = 106;
)

