
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type GameDJ001Conf struct {
    _dataMap map[int32]*GameDJ001ConfData
    _dataList []*GameDJ001ConfData
}

func NewGameDJ001Conf(_buf []map[string]interface{}) (*GameDJ001Conf, error) {
    _dataList := make([]*GameDJ001ConfData, 0, len(_buf))
    dataMap := make(map[int32]*GameDJ001ConfData)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGameDJ001ConfData(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &GameDJ001Conf{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *GameDJ001Conf) GetDataMap() map[int32]*GameDJ001ConfData {
    return table._dataMap
}

func (table *GameDJ001Conf) GetDataList() []*GameDJ001ConfData {
    return table._dataList
}

func (table *GameDJ001Conf) Get(key int32) *GameDJ001ConfData {
    return table._dataMap[key]
}


