
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type LocalizeConfig struct {
    Key string
    TextCn string
    TextEn string
    TextJp string
    TextKr string
}

const TypeId_LocalizeConfig = -1797730613

func (*LocalizeConfig) GetTypeId() int32 {
    return -1797730613
}

func NewLocalizeConfig(_buf map[string]interface{}) (_v *LocalizeConfig, err error) {
    _v = &LocalizeConfig{}
    { var _ok_ bool; if _v.Key, _ok_ = _buf["key"].(string); !_ok_ { err = errors.New("key error"); return } }
    { var _ok_ bool; if _v.TextCn, _ok_ = _buf["text_cn"].(string); !_ok_ { err = errors.New("text_cn error"); return } }
    { var _ok_ bool; if _v.TextEn, _ok_ = _buf["text_en"].(string); !_ok_ { err = errors.New("text_en error"); return } }
    { var _ok_ bool; if _v.TextJp, _ok_ = _buf["text_jp"].(string); !_ok_ { err = errors.New("text_jp error"); return } }
    { var _ok_ bool; if _v.TextKr, _ok_ = _buf["text_kr"].(string); !_ok_ { err = errors.New("text_kr error"); return } }
    return
}

