
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

type JsonLoader func(string) ([]map[string]interface{}, error)

type Tables struct {
    Global *GameGlobal
    AGameConf *GameAGameConf
    PlayerLv *GamePlayerLv
    PlayerBuff *GamePlayerBuff
    DJ001Conf *GameDJ001Conf
    BR002Conf *GameBR002Conf
    DJ002Conf *GameDJ002Conf
    BR003Conf *GameBR003Conf
    BR003Room *GameBR003Room
    BR004Conf *GameBR004Conf
}

func NewTables(loader JsonLoader) (*Tables, error) {
    var err error
    var buf []map[string]interface{}

    tables := &Tables{}
    if buf, err = loader("game_global") ; err != nil {
        return nil, err
    }
    if tables.Global, err = NewGameGlobal(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("game_agameconf") ; err != nil {
        return nil, err
    }
    if tables.AGameConf, err = NewGameAGameConf(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("game_playerlv") ; err != nil {
        return nil, err
    }
    if tables.PlayerLv, err = NewGamePlayerLv(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("game_playerbuff") ; err != nil {
        return nil, err
    }
    if tables.PlayerBuff, err = NewGamePlayerBuff(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("game_dj001conf") ; err != nil {
        return nil, err
    }
    if tables.DJ001Conf, err = NewGameDJ001Conf(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("game_br002conf") ; err != nil {
        return nil, err
    }
    if tables.BR002Conf, err = NewGameBR002Conf(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("game_dj002conf") ; err != nil {
        return nil, err
    }
    if tables.DJ002Conf, err = NewGameDJ002Conf(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("game_br003conf") ; err != nil {
        return nil, err
    }
    if tables.BR003Conf, err = NewGameBR003Conf(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("game_br003room") ; err != nil {
        return nil, err
    }
    if tables.BR003Room, err = NewGameBR003Room(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("game_br004conf") ; err != nil {
        return nil, err
    }
    if tables.BR004Conf, err = NewGameBR004Conf(buf) ; err != nil {
        return nil, err
    }
    return tables, nil
}


